#!/bin/bash
#SBATCH --partition=gpu4_medium
#SBATCH --job-name=NOISE
#SBATCH --mem-per-cpu=3G
#SBATCH --time=3-00:00:00
#SBATCH --tasks=1
#SBATCH --cpus-per-task=40
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:4
srun /gpfs/data/glimcherlab/BoShen/Noise/modelfit/batch

