#!/bin/bash
#SBATCH --partition=a100_long
#SBATCH --job-name=FixMs
#SBATCH --mem-per-cpu=6G
#SBATCH --time=28-00:00:00
#SBATCH --tasks=1
#SBATCH --cpus-per-task=40
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:4
#SBATCH --mail-type=END
#SBATCH --mail-user=bs3667@nyu.edu
cd /gpfs/data/glimcherlab/BoShen/Noise/UnusedCodeorForFutureAnalyses/ReAnalyzeLouie2013
module load cuda/11.8
module load matlab/R2021b
matlab -nodisplay -r ModelFit_FastBADS_FixMs
