#!/bin/bash
#SBATCH --partition=gpu8_medium
#SBATCH --job-name=FixMs
#SBATCH --mem-per-cpu=6G
#SBATCH --time=3-00:00:00
#SBATCH --tasks=1
#SBATCH --cpus-per-task=40
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:8
#SBATCH --mail-type=END
#SBATCH --mail-user=bs3667@nyu.edu
cd /gpfs/data/glimcherlab/BoShen/Noise/UnusedCodeorForFutureAnalyses/ReAnalyszeGluth2020
module load cuda/11.8
module load matlab/R2021b
matlab -nodisplay -r ModelFit_FastBADS_FixMs
