#!/bin/bash
#SBATH --partition=a100_short
#SBATCH --job-name=NsFg2
#SBATCH --mem=360G
#SBATCH --time=3-00:00:00
#SBATCH --cpus-per-task=40
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:a100:4
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=bs3667@nyu.edu
srun /gpfs/data/glimcherlab/BoShen/Noise/Prediction/batch

