#!/bin/bash
#SBATH --partition=a100_dev
#SBATCH --job-name=Fig4
#SBATCH --mem=300G
#SBATCH --time=04:00:00
#SBATCH --cpus-per-task=48
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:a100:4
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=bs3667@nyu.edu
srun /gpfs/data/glimcherlab/BoShen/Noise/ModelSimulationCode/batch
