#!/bin/bash
#SBATH --partition=a100_dev
#SBATCH --job-name=Sim
#SBATCH --mem-per-cpu=6G
#SBATCH --time=04:00:00
#SBATCH --tasks=1
#SBATCH --cpus-per-task=48
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:4
#SBATCH --mail-type=END
#SBATCH --mail-user=bs3667@nyu.edu
cd /gpfs/data/glimcherlab/BoShen/Noise/ModelSimulationCode
module load cuda/11.8
module load matlab/R2021b
matlab -nodisplay -r Fig4

